credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Docker Hub login"
          id: "docker-hub-creds"
          password: "{AQAAABAAAAAwcX2fn9/RWq7/wm9EufzZI3RxKR1ECie/vp1+XbUUyBDPfbz6LFUhqEBv1DhFrLMrYNzxvmIDdZMu2kJsdDh6Ug==}"
          scope: GLOBAL
          username: "pkonieczny321"
      - usernamePassword:
          description: "Pulling/pushing to GitHub"
          id: "github-creds"
          password: "{AQAAABAAAAGQljp+kuMYYs8IXCOAOx+XhSr2cauzQ9YgNj6qghfLWhlbw0YMkkvClWT8SXVVq/45jGZFS0bfyjsLCf9FNVxIyo/saBC3AwPu1S9/k2gdfBgBhRTnPOmDJrWigeXNKHhtgczJCaUCeA7WKTnjCLlSiA6AJ4xY2wmVxhzujGJKj/MvZMoxrUQ5xtQ/Ozcqr7fYWvJsCEHbqYklX+ftV7Vss2dIQlI1XYgHd6wOx+tZBTo4QN2aDFXiqJ2gn4YstTV9SYSkJ/BfPuKqAKfuhbWcy2JauvZ+8qqr5IHB/pvCA6sjmY0vE7k/iTBZiFoxzZSMdvUJ30OUNs9f9r1OYa/xSq1t6ZGeqVvH+St/D0XJGt68JFRl1fyxNIphKRO5t+2QQ9fE38NaXF/yFl+DTR7f9mTVqW8H6FioLQzJuekpLa5l2oVWNuno/wPnPSGvpfFGkoBJQMSIJN7mvi0+i237r0WqAzbRE6I/a7v7DKyYY7JzJ55iLbAfdZu6Y+D8Mm4H0OEigYmpPPe1A3jmyML96xtlIFo/ya8da5SesP2dBKM=}"
          scope: GLOBAL
          username: "lolek1979"
      - string:
          description: "Argo CD API token for deployments"
          id: "argocd-token"
          scope: GLOBAL
          secret: "{AQAAABAAAADQeUtFInsJ9Q8vmJVRIHAAFpDWqOfrXS/xW63PebeDx/ivjBiLj86Ln+vKgY6ZS4LJnSaLFPqaKN+9DorYw57fuynlUdjQ5cGCgiXTH5UnWpII7t2FGiY2vK4pcNM5kJ1nzCZry4bpdE7YtADcigmoFztzHO54Pl+fnvmyJfps1H+rvoMjMOpNa/4oCbf/DpNY1LKs8UZXBt36w64LqmXEX65OR1/Ap3a2OxCgvn2xJsfWygI9QghWvRVIpo6+Qd+rOOoTqmwCsP/Gw3+aNs5ME/cnFH5NvF7ZbOlSBM2q6c4=}"
jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      name: "kubernetes"
      namespace: "jenkins"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      serverUrl: "https://kubernetes.default"
      templates:
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          image: "jenkins/inbound-agent:3301.v4363ddcca_4e7-3"
          name: "jnlp"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins/agent"
        id: "d5e6f291-c609-4adf-8f2c-68c85ae7cb42"
        label: "jenkins-jenkins-agent"
        name: "jenkins-jenkins-agent"
        namespace: "jenkins"
        nodeUsageMode: NORMAL
        podRetention: "never"
        serviceAccount: "jenkins"
        yamlMergeStrategy: "override"
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.jenkins.svc.cluster.local:8080/"
          image: "pkonieczny321/jenkins-docker-agent:latest"
          name: "jnlp"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins/agent"
        id: "383b2e23-f0d6-45d9-88d3-30ec5f026579"
        label: "docker-agent"
        name: "docker-agent"
        namespace: "jenkins"
        nodeUsageMode: NORMAL
        podRetention: "never"
        runAsUser: "0"
        serviceAccount: "jenkins"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
            readOnly: false
        yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: true
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  - "hudson.diagnosis.ReverseProxySetupMonitor"
  labelAtoms:
  - name: "built-in"
  - name: "docker-agent"
  - name: "jenkins-jenkins-agent"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "Jenkins Admin"
        properties:
        - "apiToken"
        - "consoleUrlProvider"
        - "mailer"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
jobs:
  - script: >
      pipelineJob('autotest-creds') {
        definition {
            cpsScm {
                scm {
                    git {
                        remote {
                            url('https://github.com/lolek1979/k8s-infra.git')
                            credentials('github-creds')
                        }
                        branches('main')
                    }
                }
                scriptPath('jenkins/creds-test.Jenkinsfile')
            }
        }
      }
# jobs:
#   - script: >
#       pipelineJob('sw-movie-app') {
#         properties {
#           parametersDefinitionProperty {
#             parameterDefinitions {
#               stringParameterDefinition {
#                 name('imageName')
#                 defaultValue('pkonieczny321/sw-movie-app')
#                 description('Docker image name')
#               }
#               stringParameterDefinition {
#                 name('imageTag')
#                 defaultValue('1.0.0')
#                 description('Docker image tag')
#               }
#             }
#           }
#         }

#         definition {
#           cpsScm {
#             lightweight(true)
#             scm {
#               git {
#                 remote {
#                   url('https://github.com/lolek1979/sw-movie-app-k8s.git')
#                   credentials('github-creds')
#                 }
#                 branches('*/main')
#               }
#             }
#             scriptPath('Jenkinsfile')
#           }
#         }
#       }
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: PRISM
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  cps:
    hideSandbox: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  scriptApproval:
    forceSandbox: false
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  globalLibraries:
    libraries:
    - defaultVersion: "main"
      name: "jenkins-shared-library"
      retriever:
        modernSCM:
          libraryPath: "./"
          scm:
            git:
              credentialsId: "github-creds"
              id: "b2b2040f-29af-4690-b3a2-b1cee3e9acbf"
              remote: "https://github.com/lolek1979/jenkins-shared-library.git"
              traits:
              - "gitBranchDiscovery"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://jenkins.k8s.orb.local/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"